[package]
name = "keyboard-puns"
version = "0.1.0"
authors = ["Andrew Marshall <andrew@johnandrewmarshall.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7.1"
hashbrown = "0.1.8"
num_cpus = "1.0"

[profile.release]
debug = true
